//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Match')
export class MatchEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('date', { nullable: true })
  date: Date;

  @Column('text', { nullable: true })
  opponent: string;

  @Column('text', { nullable: true })
  final_score: string;

  @Column('text', { nullable: true })
  location: string;
}
