//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Playerstatistic')
export class PlayerstatisticEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  player_id: number;

  @Column('integer', { nullable: true })
  match_id: number;

  @Column('integer', { nullable: true })
  goals: number;

  @Column('integer', { nullable: true })
  assists: number;

  @Column('integer', { nullable: true })
  appearances: number;

  @Column('integer', { nullable: true })
  minutes_played: number;
}
