//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Player')
export class PlayerEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  position: string;

  @Column('integer', { nullable: true })
  jersey_number: number;

  @Column('integer', { nullable: true })
  age: number;
}
