//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const PlayerstatisticTitle = () => {
  const record = useRecordContext();
  return <span>Playerstatistic {record ? `"${record.player_id}"` : ''}</span>;
};

export const PlayerstatisticList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="player_id" reference="Player" />
      <ReferenceField source="match_id" reference="Match" />
      <NumberField source="goals" />
      <NumberField source="assists" />
      <NumberField source="appearances" />
      <NumberField source="minutes_played" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const PlayerstatisticEdit = () => (
  <Edit title={<PlayerstatisticTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="player_id" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="match_id" reference="Match" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="goals" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="assists" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="appearances" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="minutes_played" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const PlayerstatisticCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="player_id" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="match_id" reference="Match" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="goals" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="assists" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="appearances" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="minutes_played" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="player_id"
    label="player_id"
    reference="Player"
    alwaysOn
  />,
  <ReferenceInput
    source="match_id"
    label="match_id"
    reference="Match"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
];
