//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="TeamStats" />
    <CardContent>
      TeamStats will allow users to manage information about a sports team. It
      should store players (name, position), matches (date, opponent, final
      score), and player statistics such as goals, assists and appearances. The
      app should relate players to matches via their appearances and keep track
      of team and player scores.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
